export const SUBSCRIPTIONS = [
  {
    id: 'free',
    name: 'Бесплатный план',
    price: 0,
    pointsPrice: 0,
    keys: '0',
    monthlyLimits: '0',
    extraLimits: '20 000',
    extraLimitsCost: '880 ₽',
    extraKeysPack: '—',
    extraKeyCost: '—',
    description: 'Стартовый бесплатный план для знакомства с сервисом AlfaStat.',
    features: [
      '0 ключей в тарифе',
      '0 лимитов в месяц',
      'Доп. лимиты — 20 000 (880 ₽)',
      'Без дополнительных ключей',
    ],
    cashbackPercent: 0,
  },
  {
    id: 'basic',
    name: 'Базовый',
    price: 990,
    pointsPrice: 990,
    keys: '2 000',
    monthlyLimits: '20 000',
    extraLimits: '10 000',
    extraLimitsCost: '440 ₽',
    extraKeysPack: 'от 100',
    extraKeyCost: '1 ₽ / 1 ключ',
    description: 'Базовый тариф для небольших задач и старта работы.',
    features: [
      '2 000 ключей в тарифе',
      '20 000 лимитов в месяц',
      'Доп. лимиты — 10 000 (440 ₽)',
      'Доп. пакет ключей: от 100 (1 ₽/ключ)',
    ],
    cashbackPercent: 10,
  },
  {
    id: 'starter',
    name: 'Стартовый',
    price: 2990,
    pointsPrice: 2990,
    keys: '5 000',
    monthlyLimits: '45 000',
    extraLimits: '10 000',
    extraLimitsCost: '440 ₽',
    extraKeysPack: 'от 100',
    extraKeyCost: '1 ₽ / 1 ключ',
    description: 'Расширенные возможности для активных пользователей.',
    features: [
      '5 000 ключей в тарифе',
      '45 000 лимитов в месяц',
      'Доп. лимиты — 10 000 (440 ₽)',
      'Доп. пакет ключей: от 100 (1 ₽/ключ)',
    ],
    cashbackPercent: 10,
    popular: true,
  },
  {
    id: 'advanced',
    name: 'Продвинутый',
    price: 9990,
    pointsPrice: 9990,
    keys: '12 000',
    monthlyLimits: '90 000',
    extraLimits: '10 000',
    extraLimitsCost: '440 ₽',
    extraKeysPack: 'от 100',
    extraKeyCost: '1 ₽ / 1 ключ',
    description: 'Тариф для профессиональных задач и больших объёмов.',
    features: [
      '12 000 ключей в тарифе',
      '90 000 лимитов в месяц',
      'Доп. лимиты — 10 000 (440 ₽)',
      'Доп. пакет ключей: от 100 (1 ₽/ключ)',
    ],
    cashbackPercent: 12,
  },
  {
    id: 'corporate',
    name: 'Корпоративный',
    price: 29990,
    pointsPrice: 29990,
    keys: '30 000',
    monthlyLimits: '150 000',
    extraLimits: '10 000',
    extraLimitsCost: '440 ₽',
    extraKeysPack: 'от 100',
    extraKeyCost: '1 ₽ / 1 ключ',
    description: 'Для команд и компаний с большим объёмом работы.',
    features: [
      '30 000 ключей в тарифе',
      '150 000 лимитов в месяц',
      'Доп. лимиты — 10 000 (440 ₽)',
      'Доп. пакет ключей: от 100 (1 ₽/ключ)',
    ],
    cashbackPercent: 15,
  },
  {
    id: 'individual',
    name: 'Индивидуальный',
    price: null,
    pointsPrice: null,
    keys: 'Неограниченно',
    monthlyLimits: 'Неограниченно',
    extraLimits: '—',
    extraLimitsCost: '—',
    extraKeysPack: '—',
    extraKeyCost: '—',
    description: 'Индивидуальные условия по запросу. Свяжитесь с менеджером.',
    features: [
      'Неограниченно ключей',
      'Неограниченно лимитов в месяц',
      'Индивидуальные условия',
      'Персональный менеджер',
    ],
    cashbackPercent: 0,
    isCustom: true,
  },
];

export const WELCOME_BONUS = 1500;
export const DAILY_BONUS = 100;
export const SUBSCRIPTION_DURATION_DAYS = 30;

export const getSubscriptionById = (id) =>
  SUBSCRIPTIONS.find((s) => s.id === id) || SUBSCRIPTIONS[0];
